version: '3.1'

services:
  postgresql_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql

  cache:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: ['--requirepass "secret"']

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresql_db

volumes:
  postgres:
