version: '3.1'

services:
  mysql_db:
    image: mysql
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: mydb
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

  cache:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: ['--requirepass "secret"']

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db

volumes:
  mysql:
