version: '3.7'

services:
  server:
    ports:
      - 4000:4000
    depends_on:
      - mysqldb
      - cache

  mysqldb:
    image: mysql:8.0.28-oracle
    command: --authentication_policy=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    cap_add:
      - SYS_NICE # CAP_SYS_NICE

  cache:
    image: redis:7.0.0-alpine
    command:
      [
        "sh",
        "-c",
        "redis-server --requirepass \"$REDIS_PASSWORD\""
      ]
