version: '3.7'

services:
  server:
    build:
      context: .
      args:
        - NODE_ENV=development
    env_file:
      - .env
    restart: on-failure
    links:
      - mysqldb
      - cache
    volumes:
      - /app/node_modules
      - ./:/app
    command: npm run dev
        
  mysqldb:
    restart: on-failure
    env_file:
      - .env
    volumes:
      - mysql_dev:/var/lib/mysql

  cache:
    restart: on-failure
    env_file:
      - .env

volumes:
  mysql_dev:
    driver: local
