version: '3.7'

services:
  server:
    tty: true
    build:
      context: .
      args:
        - NODE_ENV=development
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/prisma/migrations
    command: [ "bash", "-c", "./db_deploy.sh && npm run dev" ]

  mysqldb:
    tty: true
    restart: on-failure
    env_file:
      - .env
    volumes:
      - mysql_dev:/var/lib/mysql

  cache:
    tty: true
    restart: on-failure
    env_file:
      - .env
    volumes:
      - cache_dev:/data

volumes:
  mysql_dev:
    driver: local
  cache_dev:
    driver: local
