version: '3.7'

services:
  server:
    entrypoint: ./db_deploy.sh
    ports:
      - $APP_PORT:4000
    depends_on:
      - mysqldb
      - cache

  mysqldb:
    image: mysql:8
    command: --authentication_policy=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    ports:
      - $DB_PORT:3306
    cap_add:
      - SYS_NICE # CAP_SYS_NICE

  cache:
    image: redis:alpine
    ports:
      - $REDIS_PORT:6379
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
