version: '3.7'

services:
  server:
    build: .
    restart: on-failure
    links:
      - mysqldb
      - cache
    env_file:
      - .env
    environment:
      - NODE_ENV=test
    command: npm run exec-tests

  mysqldb:
    restart: on-failure
    env_file:
      - .env
    volumes:
      - mysql_test:/var/lib/mysql

  cache:
    restart: on-failure
    env_file:
      - .env

volumes:
  mysql_test:
    driver: local
