version: '3.1'

services:
  server:
    build: .
    image: shahandocker1986/my_project
    restart: always
    env_file:
      - .env
    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - mysqldb
      - cache
    networks:
      - my_project
    links:
      - mysqldb
      - cache

  mysqldb:
    image: mysql
    command: --authentication_policy=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME  
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    ports:
      - $DB_PORT:$DB_PORT
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - my_project

  cache:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - $REDIS_PORT:$REDIS_PORT
    command: ['--requirepass $REDIS_PASSWORD']
    networks:
      - my_project

networks:
  my_project:
    driver: bridge
